allow json library to be configurable, run `mix format`
bechurch/auth0_jwks pull request #3
Opened 2020-05-15 00:50 UTC by mus0u

howdy folks! thanks so much for this library. it's been working like a charm for me so far. i really appreciate y'all putting it out there for randos like myself.

one thing i did wish for was the ability to configure what JSON codec library was being used to decode the user info. most of my projects use [Jason](https://github.com/michalmuskala/jason) for this, so this was the only library that was pulling in Poison into my deps. the interface is basically the same between the two libraries, and other projects, most notably Phoenix, have made the choice of JSON library configurable. i've chosen to emulate the name of Phoenix's configuration setting in this PR, but i don't really have any preference on the name. it just seemed like a reasonable choice.

i also ran `mix format` at the root of the project, because i noticed that my Emacs was autoformatting some things on save, and i wanted everything to be uniform. if you'd prefer a version of this PR without any formatting changes, i completely understand (i have my own beef with a few of mix format's aesthetic choices...), and i'm happy to submit an alternate version that just adds the config changes, if that'd be preferable to y'all.

anyway, if this PR is entirely unwelcome, then i apologize and please close it without a second thought! i just thought i'd offer it up, since it made my life a little bit easier. if it is welcome, then i hope i've made it easy to integrate. i have some ideas for other small features i might want to offer, such as facilities for stubbing the HTTP call in test mode with Mox, if it's amenable to y'all.

thanks for reading, and have a great week!

2020-05-15 00:51 UTC, mus0u commented on lib/config.ex
> +  def json_library, do: Application.get_env(:auth0_jwks, :json_library) || Poison
here is the first non-`mix format`-based change in this PR...

2020-05-15 00:51 UTC, mus0u commented on lib/user_info.ex
> +  alias Auth0Jwks.Config
here is the second non-`mix format`-based change in this PR...

2020-05-15 00:52 UTC, mus0u commented on lib/user_info.ex
> +      |> Config.json_library().decode()
...and here's the last one. everything else was just `mix format`. hopefully this makes it easy to read.

2020-05-15 00:53 UTC, mus0u commented on mix.exs
> +      {:poison, "~> 4.0", optional: true}
this is the last one. everything else was just `mix format`. hopefully this makes it easy to read.

2020-06-03 19:54 UTC, bnchrch requested changes
@mus0u Hey thanks for the PR! So sorry for the late review I just saw this!

Anyway this seems fine to merge, if you'd be so kind to remove the todo and just update the readme to include the json_library feature!

2020-06-03 19:54 UTC, bechurch commented on lib/token.ex
> +    # todo create util
Could we remove this todo?

2020-11-17 03:12 UTC, merged